/*
 * LogSentinel RESTful API
 * Read more at http://localhost:8080/docs
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Application
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T10:33:18.929+03:00")
public class Application {
  @SerializedName("containsPersonalData")
  private Boolean containsPersonalData = null;

  @SerializedName("created")
  private DateTime created = null;


  @SerializedName("detailsTransformationScript")
  private String detailsTransformationScript = null;

  @SerializedName("genesisEntryId")
  private String genesisEntryId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("ipWhiteList")
  private List<String> ipWhiteList = null;

  @SerializedName("latestEthereumTxHash")
  private String latestEthereumTxHash = null;

  @SerializedName("latestGlacierArchiveId")
  private String latestGlacierArchiveId = null;

  @SerializedName("latestHashRecipientEmails")
  private List<String> latestHashRecipientEmails = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("organizationId")
  private String organizationId = null;

  @SerializedName("partialVerificationPeriodMinutes")
  private Integer partialVerificationPeriodMinutes = null;

  @SerializedName("signatureVerificationPublicKeys")
  private List<String> signatureVerificationPublicKeys = null;

  @SerializedName("storeHashesInEthereum")
  private Boolean storeHashesInEthereum = null;

  @SerializedName("updated")
  private DateTime updated = null;

  @SerializedName("verificationFailureReportRecipientEmails")
  private List<String> verificationFailureReportRecipientEmails = null;

  @SerializedName("verificationPeriodMinutes")
  private Integer verificationPeriodMinutes = null;

  public Application containsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
    return this;
  }

   /**
   * Get containsPersonalData
   * @return containsPersonalData
  **/
  @ApiModelProperty(value = "")
  public Boolean isContainsPersonalData() {
    return containsPersonalData;
  }

  public void setContainsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
  }

  public Application created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public Application detailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
    return this;
  }

   /**
   * Get detailsTransformationScript
   * @return detailsTransformationScript
  **/
  @ApiModelProperty(value = "")
  public String getDetailsTransformationScript() {
    return detailsTransformationScript;
  }

  public void setDetailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
  }

  public Application genesisEntryId(String genesisEntryId) {
    this.genesisEntryId = genesisEntryId;
    return this;
  }

   /**
   * Get genesisEntryId
   * @return genesisEntryId
  **/
  @ApiModelProperty(value = "")
  public String getGenesisEntryId() {
    return genesisEntryId;
  }

  public void setGenesisEntryId(String genesisEntryId) {
    this.genesisEntryId = genesisEntryId;
  }

  public Application id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Application ipWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
    return this;
  }

  public Application addIpWhiteListItem(String ipWhiteListItem) {
    if (this.ipWhiteList == null) {
      this.ipWhiteList = new ArrayList<String>();
    }
    this.ipWhiteList.add(ipWhiteListItem);
    return this;
  }

   /**
   * Get ipWhiteList
   * @return ipWhiteList
  **/
  @ApiModelProperty(value = "")
  public List<String> getIpWhiteList() {
    return ipWhiteList;
  }

  public void setIpWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
  }

  public Application latestEthereumTxHash(String latestEthereumTxHash) {
    this.latestEthereumTxHash = latestEthereumTxHash;
    return this;
  }

   /**
   * Get latestEthereumTxHash
   * @return latestEthereumTxHash
  **/
  @ApiModelProperty(value = "")
  public String getLatestEthereumTxHash() {
    return latestEthereumTxHash;
  }

  public void setLatestEthereumTxHash(String latestEthereumTxHash) {
    this.latestEthereumTxHash = latestEthereumTxHash;
  }

  public Application latestGlacierArchiveId(String latestGlacierArchiveId) {
    this.latestGlacierArchiveId = latestGlacierArchiveId;
    return this;
  }

   /**
   * Get latestGlacierArchiveId
   * @return latestGlacierArchiveId
  **/
  @ApiModelProperty(value = "")
  public String getLatestGlacierArchiveId() {
    return latestGlacierArchiveId;
  }

  public void setLatestGlacierArchiveId(String latestGlacierArchiveId) {
    this.latestGlacierArchiveId = latestGlacierArchiveId;
  }

  public Application latestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
    return this;
  }

  public Application addLatestHashRecipientEmailsItem(String latestHashRecipientEmailsItem) {
    if (this.latestHashRecipientEmails == null) {
      this.latestHashRecipientEmails = new ArrayList<String>();
    }
    this.latestHashRecipientEmails.add(latestHashRecipientEmailsItem);
    return this;
  }

   /**
   * Get latestHashRecipientEmails
   * @return latestHashRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getLatestHashRecipientEmails() {
    return latestHashRecipientEmails;
  }

  public void setLatestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
  }

  public Application name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Application organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public Application partialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
    return this;
  }

   /**
   * Get partialVerificationPeriodMinutes
   * @return partialVerificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getPartialVerificationPeriodMinutes() {
    return partialVerificationPeriodMinutes;
  }

  public void setPartialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
  }

  public Application signatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
    return this;
  }

  public Application addSignatureVerificationPublicKeysItem(String signatureVerificationPublicKeysItem) {
    if (this.signatureVerificationPublicKeys == null) {
      this.signatureVerificationPublicKeys = new ArrayList<String>();
    }
    this.signatureVerificationPublicKeys.add(signatureVerificationPublicKeysItem);
    return this;
  }

   /**
   * Get signatureVerificationPublicKeys
   * @return signatureVerificationPublicKeys
  **/
  @ApiModelProperty(value = "")
  public List<String> getSignatureVerificationPublicKeys() {
    return signatureVerificationPublicKeys;
  }

  public void setSignatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
  }

  public Application storeHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
    return this;
  }

   /**
   * Get storeHashesInEthereum
   * @return storeHashesInEthereum
  **/
  @ApiModelProperty(value = "")
  public Boolean isStoreHashesInEthereum() {
    return storeHashesInEthereum;
  }

  public void setStoreHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
  }

  public Application updated(DateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public DateTime getUpdated() {
    return updated;
  }

  public void setUpdated(DateTime updated) {
    this.updated = updated;
  }

  public Application verificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
    return this;
  }

  public Application addVerificationFailureReportRecipientEmailsItem(String verificationFailureReportRecipientEmailsItem) {
    if (this.verificationFailureReportRecipientEmails == null) {
      this.verificationFailureReportRecipientEmails = new ArrayList<String>();
    }
    this.verificationFailureReportRecipientEmails.add(verificationFailureReportRecipientEmailsItem);
    return this;
  }

   /**
   * Get verificationFailureReportRecipientEmails
   * @return verificationFailureReportRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getVerificationFailureReportRecipientEmails() {
    return verificationFailureReportRecipientEmails;
  }

  public void setVerificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
  }

  public Application verificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
    return this;
  }

   /**
   * Get verificationPeriodMinutes
   * @return verificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getVerificationPeriodMinutes() {
    return verificationPeriodMinutes;
  }

  public void setVerificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.containsPersonalData, application.containsPersonalData) &&
        Objects.equals(this.created, application.created) &&
        Objects.equals(this.detailsTransformationScript, application.detailsTransformationScript) &&
        Objects.equals(this.genesisEntryId, application.genesisEntryId) &&
        Objects.equals(this.id, application.id) &&
        Objects.equals(this.ipWhiteList, application.ipWhiteList) &&
        Objects.equals(this.latestEthereumTxHash, application.latestEthereumTxHash) &&
        Objects.equals(this.latestGlacierArchiveId, application.latestGlacierArchiveId) &&
        Objects.equals(this.latestHashRecipientEmails, application.latestHashRecipientEmails) &&
        Objects.equals(this.name, application.name) &&
        Objects.equals(this.organizationId, application.organizationId) &&
        Objects.equals(this.partialVerificationPeriodMinutes, application.partialVerificationPeriodMinutes) &&
        Objects.equals(this.signatureVerificationPublicKeys, application.signatureVerificationPublicKeys) &&
        Objects.equals(this.storeHashesInEthereum, application.storeHashesInEthereum) &&
        Objects.equals(this.updated, application.updated) &&
        Objects.equals(this.verificationFailureReportRecipientEmails, application.verificationFailureReportRecipientEmails) &&
        Objects.equals(this.verificationPeriodMinutes, application.verificationPeriodMinutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containsPersonalData, created, detailsTransformationScript, genesisEntryId, id, ipWhiteList, latestEthereumTxHash, latestGlacierArchiveId, latestHashRecipientEmails, name, organizationId, partialVerificationPeriodMinutes, signatureVerificationPublicKeys, storeHashesInEthereum, updated, verificationFailureReportRecipientEmails, verificationPeriodMinutes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    
    sb.append("    containsPersonalData: ").append(toIndentedString(containsPersonalData)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    detailsTransformationScript: ").append(toIndentedString(detailsTransformationScript)).append("\n");
    sb.append("    genesisEntryId: ").append(toIndentedString(genesisEntryId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ipWhiteList: ").append(toIndentedString(ipWhiteList)).append("\n");
    sb.append("    latestEthereumTxHash: ").append(toIndentedString(latestEthereumTxHash)).append("\n");
    sb.append("    latestGlacierArchiveId: ").append(toIndentedString(latestGlacierArchiveId)).append("\n");
    sb.append("    latestHashRecipientEmails: ").append(toIndentedString(latestHashRecipientEmails)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    partialVerificationPeriodMinutes: ").append(toIndentedString(partialVerificationPeriodMinutes)).append("\n");
    sb.append("    signatureVerificationPublicKeys: ").append(toIndentedString(signatureVerificationPublicKeys)).append("\n");
    sb.append("    storeHashesInEthereum: ").append(toIndentedString(storeHashesInEthereum)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    verificationFailureReportRecipientEmails: ").append(toIndentedString(verificationFailureReportRecipientEmails)).append("\n");
    sb.append("    verificationPeriodMinutes: ").append(toIndentedString(verificationPeriodMinutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

