/*
 * LogSentinel RESTful API
 * Read more at https://logsentinel.com/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ConsistencyProof
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-02T11:34:18.314+03:00")
public class ConsistencyProof {
  @SerializedName("firstHash")
  private String firstHash = null;

  @SerializedName("firstTreeSize")
  private Integer firstTreeSize = null;

  @SerializedName("path")
  private List<String> path = null;

  @SerializedName("secondHash")
  private String secondHash = null;

  @SerializedName("secondTreeSize")
  private Integer secondTreeSize = null;

  public ConsistencyProof firstHash(String firstHash) {
    this.firstHash = firstHash;
    return this;
  }

   /**
   * Get firstHash
   * @return firstHash
  **/
  @ApiModelProperty(value = "")
  public String getFirstHash() {
    return firstHash;
  }

  public void setFirstHash(String firstHash) {
    this.firstHash = firstHash;
  }

  public ConsistencyProof firstTreeSize(Integer firstTreeSize) {
    this.firstTreeSize = firstTreeSize;
    return this;
  }

   /**
   * Get firstTreeSize
   * @return firstTreeSize
  **/
  @ApiModelProperty(value = "")
  public Integer getFirstTreeSize() {
    return firstTreeSize;
  }

  public void setFirstTreeSize(Integer firstTreeSize) {
    this.firstTreeSize = firstTreeSize;
  }

  public ConsistencyProof path(List<String> path) {
    this.path = path;
    return this;
  }

  public ConsistencyProof addPathItem(String pathItem) {
    if (this.path == null) {
      this.path = new ArrayList<String>();
    }
    this.path.add(pathItem);
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @ApiModelProperty(value = "")
  public List<String> getPath() {
    return path;
  }

  public void setPath(List<String> path) {
    this.path = path;
  }

  public ConsistencyProof secondHash(String secondHash) {
    this.secondHash = secondHash;
    return this;
  }

   /**
   * Get secondHash
   * @return secondHash
  **/
  @ApiModelProperty(value = "")
  public String getSecondHash() {
    return secondHash;
  }

  public void setSecondHash(String secondHash) {
    this.secondHash = secondHash;
  }

  public ConsistencyProof secondTreeSize(Integer secondTreeSize) {
    this.secondTreeSize = secondTreeSize;
    return this;
  }

   /**
   * Get secondTreeSize
   * @return secondTreeSize
  **/
  @ApiModelProperty(value = "")
  public Integer getSecondTreeSize() {
    return secondTreeSize;
  }

  public void setSecondTreeSize(Integer secondTreeSize) {
    this.secondTreeSize = secondTreeSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsistencyProof consistencyProof = (ConsistencyProof) o;
    return Objects.equals(this.firstHash, consistencyProof.firstHash) &&
        Objects.equals(this.firstTreeSize, consistencyProof.firstTreeSize) &&
        Objects.equals(this.path, consistencyProof.path) &&
        Objects.equals(this.secondHash, consistencyProof.secondHash) &&
        Objects.equals(this.secondTreeSize, consistencyProof.secondTreeSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstHash, firstTreeSize, path, secondHash, secondTreeSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsistencyProof {\n");

    sb.append("    firstHash: ").append(toIndentedString(firstHash)).append("\n");
    sb.append("    firstTreeSize: ").append(toIndentedString(firstTreeSize)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    secondHash: ").append(toIndentedString(secondHash)).append("\n");
    sb.append("    secondTreeSize: ").append(toIndentedString(secondTreeSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

