/*
 * LogSentinel RESTful API
 * Read more at https://logsentinel.com/documentation/
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TreeHead
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-02T11:34:18.314+03:00")
public class TreeHead {
  @SerializedName("rootHash")
  private String rootHash = null;

  @SerializedName("timestampToken")
  private String timestampToken = null;

  @SerializedName("treeSize")
  private Integer treeSize = null;

  public void setRootHash(String rootHash) {
    this.rootHash = rootHash;
  }

  public String getRootHash() {
    return rootHash;
  }

  public TreeHead timestampToken(String timestampToken) {
    this.timestampToken = timestampToken;
    return this;
  }

   /**
   * Get timestampToken
   * @return timestampToken
  **/
  @ApiModelProperty(value = "")
  public String getTimestampToken() {
    return timestampToken;
  }

  public void setTimestampToken(String timestampToken) {
    this.timestampToken = timestampToken;
  }

  public TreeHead treeSize(Integer treeSize) {
    this.treeSize = treeSize;
    return this;
  }

   /**
   * Get treeSize
   * @return treeSize
  **/
  @ApiModelProperty(value = "")
  public Integer getTreeSize() {
    return treeSize;
  }

  public void setTreeSize(Integer treeSize) {
    this.treeSize = treeSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreeHead treeHead = (TreeHead) o;
    return Objects.equals(this.rootHash, treeHead.rootHash) &&
        Objects.equals(this.timestampToken, treeHead.timestampToken) &&
        Objects.equals(this.treeSize, treeHead.treeSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rootHash, timestampToken, treeSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreeHead {\n");

    sb.append("    rootHash: ").append(toIndentedString(rootHash)).append("\n");
    sb.append("    timestampToken: ").append(toIndentedString(timestampToken)).append("\n");
    sb.append("    treeSize: ").append(toIndentedString(treeSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

