/*
 * LogSentinel RESTful API
 * Read more at http://localhost:8080/docs
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

import java.io.IOException;
import java.util.Objects;

/**
 * UserDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T10:33:18.929+03:00")
public class UserDetails {
  @SerializedName("admin")
  private Boolean admin = null;

  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("defaultApplicationId")
  private String defaultApplicationId = null;

  @SerializedName("defaultApplicationName")
  private String defaultApplicationName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("expirationDate")
  private LocalDate expirationDate = null;

  @SerializedName("expired")
  private Boolean expired = null;

  @SerializedName("hasPassword")
  private Boolean hasPassword = null;

  @SerializedName("id")
  private String id = null;

  /**
   * Gets or Sets language
   */
  @JsonAdapter(LanguageEnum.Adapter.class)
  public enum LanguageEnum {
    EN("EN"),

    BG("BG");

    private String value;

    LanguageEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LanguageEnum fromValue(String text) {
      for (LanguageEnum b : LanguageEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<LanguageEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LanguageEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LanguageEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return LanguageEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("language")
  private LanguageEnum language = null;

  @SerializedName("names")
  private String names = null;

  @SerializedName("organizationId")
  private String organizationId = null;

  @SerializedName("organizationName")
  private String organizationName = null;

  /**
   * Gets or Sets organizationRole
   */
  @JsonAdapter(OrganizationRoleEnum.Adapter.class)
  public enum OrganizationRoleEnum {
    ADMIN("ADMIN"),

    AUDITOR("AUDITOR"),

    DEVELOPER("DEVELOPER"),

    MANAGER("MANAGER");

    private String value;

    OrganizationRoleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OrganizationRoleEnum fromValue(String text) {
      for (OrganizationRoleEnum b : OrganizationRoleEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<OrganizationRoleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrganizationRoleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OrganizationRoleEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OrganizationRoleEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("organizationRole")
  private OrganizationRoleEnum organizationRole = null;

  @SerializedName("position")
  private String position = null;

  @SerializedName("profilePicturePath")
  private String profilePicturePath = null;

  @SerializedName("timezone")
  private String timezone = null;

  @SerializedName("twoFactorAuthEnabled")
  private Boolean twoFactorAuthEnabled = null;

  @SerializedName("twoFactorAuthKey")
  private String twoFactorAuthKey = null;

  @SerializedName("whitelabelStyling")
  private WhitelabelStyling whitelabelStyling = null;

  public UserDetails admin(Boolean admin) {
    this.admin = admin;
    return this;
  }

   /**
   * Get admin
   * @return admin
  **/
  @ApiModelProperty(value = "")
  public Boolean isAdmin() {
    return admin;
  }

  public void setAdmin(Boolean admin) {
    this.admin = admin;
  }

  public UserDetails created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public UserDetails defaultApplicationId(String defaultApplicationId) {
    this.defaultApplicationId = defaultApplicationId;
    return this;
  }

   /**
   * Get defaultApplicationId
   * @return defaultApplicationId
  **/
  @ApiModelProperty(value = "")
  public String getDefaultApplicationId() {
    return defaultApplicationId;
  }

  public void setDefaultApplicationId(String defaultApplicationId) {
    this.defaultApplicationId = defaultApplicationId;
  }

  public UserDetails defaultApplicationName(String defaultApplicationName) {
    this.defaultApplicationName = defaultApplicationName;
    return this;
  }

   /**
   * Get defaultApplicationName
   * @return defaultApplicationName
  **/
  @ApiModelProperty(value = "")
  public String getDefaultApplicationName() {
    return defaultApplicationName;
  }

  public void setDefaultApplicationName(String defaultApplicationName) {
    this.defaultApplicationName = defaultApplicationName;
  }

  public UserDetails email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserDetails expirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(LocalDate expirationDate) {
    this.expirationDate = expirationDate;
  }

  public UserDetails expired(Boolean expired) {
    this.expired = expired;
    return this;
  }

   /**
   * Get expired
   * @return expired
  **/
  @ApiModelProperty(value = "")
  public Boolean isExpired() {
    return expired;
  }

  public void setExpired(Boolean expired) {
    this.expired = expired;
  }

  public UserDetails hasPassword(Boolean hasPassword) {
    this.hasPassword = hasPassword;
    return this;
  }

   /**
   * Get hasPassword
   * @return hasPassword
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasPassword() {
    return hasPassword;
  }

  public void setHasPassword(Boolean hasPassword) {
    this.hasPassword = hasPassword;
  }

  public UserDetails id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UserDetails language(LanguageEnum language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public LanguageEnum getLanguage() {
    return language;
  }

  public void setLanguage(LanguageEnum language) {
    this.language = language;
  }

  public UserDetails names(String names) {
    this.names = names;
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @ApiModelProperty(value = "")
  public String getNames() {
    return names;
  }

  public void setNames(String names) {
    this.names = names;
  }

  public UserDetails organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public UserDetails organizationName(String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

   /**
   * Get organizationName
   * @return organizationName
  **/
  @ApiModelProperty(value = "")
  public String getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(String organizationName) {
    this.organizationName = organizationName;
  }

  public UserDetails organizationRole(OrganizationRoleEnum organizationRole) {
    this.organizationRole = organizationRole;
    return this;
  }

   /**
   * Get organizationRole
   * @return organizationRole
  **/
  @ApiModelProperty(value = "")
  public OrganizationRoleEnum getOrganizationRole() {
    return organizationRole;
  }

  public void setOrganizationRole(OrganizationRoleEnum organizationRole) {
    this.organizationRole = organizationRole;
  }

  public UserDetails position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(value = "")
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public UserDetails profilePicturePath(String profilePicturePath) {
    this.profilePicturePath = profilePicturePath;
    return this;
  }

   /**
   * Get profilePicturePath
   * @return profilePicturePath
  **/
  @ApiModelProperty(value = "")
  public String getProfilePicturePath() {
    return profilePicturePath;
  }

  public void setProfilePicturePath(String profilePicturePath) {
    this.profilePicturePath = profilePicturePath;
  }

  public UserDetails timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @ApiModelProperty(value = "")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public UserDetails twoFactorAuthEnabled(Boolean twoFactorAuthEnabled) {
    this.twoFactorAuthEnabled = twoFactorAuthEnabled;
    return this;
  }

   /**
   * Get twoFactorAuthEnabled
   * @return twoFactorAuthEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isTwoFactorAuthEnabled() {
    return twoFactorAuthEnabled;
  }

  public void setTwoFactorAuthEnabled(Boolean twoFactorAuthEnabled) {
    this.twoFactorAuthEnabled = twoFactorAuthEnabled;
  }

  public UserDetails twoFactorAuthKey(String twoFactorAuthKey) {
    this.twoFactorAuthKey = twoFactorAuthKey;
    return this;
  }

   /**
   * Get twoFactorAuthKey
   * @return twoFactorAuthKey
  **/
  @ApiModelProperty(value = "")
  public String getTwoFactorAuthKey() {
    return twoFactorAuthKey;
  }

  public void setTwoFactorAuthKey(String twoFactorAuthKey) {
    this.twoFactorAuthKey = twoFactorAuthKey;
  }

  public UserDetails whitelabelStyling(WhitelabelStyling whitelabelStyling) {
    this.whitelabelStyling = whitelabelStyling;
    return this;
  }

   /**
   * Get whitelabelStyling
   * @return whitelabelStyling
  **/
  @ApiModelProperty(value = "")
  public WhitelabelStyling getWhitelabelStyling() {
    return whitelabelStyling;
  }

  public void setWhitelabelStyling(WhitelabelStyling whitelabelStyling) {
    this.whitelabelStyling = whitelabelStyling;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDetails userDetails = (UserDetails) o;
    return Objects.equals(this.admin, userDetails.admin) &&
        Objects.equals(this.created, userDetails.created) &&
        Objects.equals(this.defaultApplicationId, userDetails.defaultApplicationId) &&
        Objects.equals(this.defaultApplicationName, userDetails.defaultApplicationName) &&
        Objects.equals(this.email, userDetails.email) &&
        Objects.equals(this.expirationDate, userDetails.expirationDate) &&
        Objects.equals(this.expired, userDetails.expired) &&
        Objects.equals(this.hasPassword, userDetails.hasPassword) &&
        Objects.equals(this.id, userDetails.id) &&
        Objects.equals(this.language, userDetails.language) &&
        Objects.equals(this.names, userDetails.names) &&
        Objects.equals(this.organizationId, userDetails.organizationId) &&
        Objects.equals(this.organizationName, userDetails.organizationName) &&
        Objects.equals(this.organizationRole, userDetails.organizationRole) &&
        Objects.equals(this.position, userDetails.position) &&
        Objects.equals(this.profilePicturePath, userDetails.profilePicturePath) &&
        Objects.equals(this.timezone, userDetails.timezone) &&
        Objects.equals(this.twoFactorAuthEnabled, userDetails.twoFactorAuthEnabled) &&
        Objects.equals(this.twoFactorAuthKey, userDetails.twoFactorAuthKey) &&
        Objects.equals(this.whitelabelStyling, userDetails.whitelabelStyling);
  }

  @Override
  public int hashCode() {
    return Objects.hash(admin, created, defaultApplicationId, defaultApplicationName, email, expirationDate, expired, hasPassword, id, language, names, organizationId, organizationName, organizationRole, position, profilePicturePath, timezone, twoFactorAuthEnabled, twoFactorAuthKey, whitelabelStyling);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDetails {\n");

    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    defaultApplicationId: ").append(toIndentedString(defaultApplicationId)).append("\n");
    sb.append("    defaultApplicationName: ").append(toIndentedString(defaultApplicationName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    hasPassword: ").append(toIndentedString(hasPassword)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    organizationRole: ").append(toIndentedString(organizationRole)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    profilePicturePath: ").append(toIndentedString(profilePicturePath)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    twoFactorAuthEnabled: ").append(toIndentedString(twoFactorAuthEnabled)).append("\n");
    sb.append("    twoFactorAuthKey: ").append(toIndentedString(twoFactorAuthKey)).append("\n");
    sb.append("    whitelabelStyling: ").append(toIndentedString(whitelabelStyling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

