/*
 * LogSentinel RESTful API
 * Read more at https://logsentinel.com/docs
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * Verification
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-24T18:34:16.973Z")
public class Verification {
  @SerializedName("applicationId")
  private String applicationId = null;

  @SerializedName("attemptedHash")
  private String attemptedHash = null;

  @SerializedName("auditLogEntryId")
  private String auditLogEntryId = null;

  @SerializedName("created")
  private DateTime created = null;

  /**
   * Gets or Sets failure
   */
  public enum FailureEnum {
    @SerializedName("HASH_NOT_FOUND")
    HASH_NOT_FOUND("HASH_NOT_FOUND"),
    
    @SerializedName("HASH_MISMATCH")
    HASH_MISMATCH("HASH_MISMATCH"),
    
    @SerializedName("SEARCH_ENGINE_AND_DB_MISMATCH")
    SEARCH_ENGINE_AND_DB_MISMATCH("SEARCH_ENGINE_AND_DB_MISMATCH"),
    
    @SerializedName("MISSING_PREVIOUS_ENTRY")
    MISSING_PREVIOUS_ENTRY("MISSING_PREVIOUS_ENTRY"),
    
    @SerializedName("MISSING_DB_ENTRY")
    MISSING_DB_ENTRY("MISSING_DB_ENTRY"),
    
    @SerializedName("TIMESTAMP_VALIDATION_FAILED")
    TIMESTAMP_VALIDATION_FAILED("TIMESTAMP_VALIDATION_FAILED"),
    
    @SerializedName("TIMESETAMP_GROUP_HASH_MISMATCH")
    TIMESETAMP_GROUP_HASH_MISMATCH("TIMESETAMP_GROUP_HASH_MISMATCH");

    private String value;

    FailureEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("failure")
  private FailureEnum failure = null;

  @SerializedName("id")
  private String id = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    @SerializedName("MANUAL")
    MANUAL("MANUAL"),
    
    @SerializedName("API_CALL")
    API_CALL("API_CALL"),
    
    @SerializedName("BACKGROUND")
    BACKGROUND("BACKGROUND");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public Verification applicationId(String applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(String applicationId) {
    this.applicationId = applicationId;
  }

  public Verification attemptedHash(String attemptedHash) {
    this.attemptedHash = attemptedHash;
    return this;
  }

   /**
   * Get attemptedHash
   * @return attemptedHash
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAttemptedHash() {
    return attemptedHash;
  }

  public void setAttemptedHash(String attemptedHash) {
    this.attemptedHash = attemptedHash;
  }

  public Verification auditLogEntryId(String auditLogEntryId) {
    this.auditLogEntryId = auditLogEntryId;
    return this;
  }

   /**
   * Get auditLogEntryId
   * @return auditLogEntryId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAuditLogEntryId() {
    return auditLogEntryId;
  }

  public void setAuditLogEntryId(String auditLogEntryId) {
    this.auditLogEntryId = auditLogEntryId;
  }

  public Verification created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public Verification failure(FailureEnum failure) {
    this.failure = failure;
    return this;
  }

   /**
   * Get failure
   * @return failure
  **/
  @ApiModelProperty(example = "null", value = "")
  public FailureEnum getFailure() {
    return failure;
  }

  public void setFailure(FailureEnum failure) {
    this.failure = failure;
  }

  public Verification id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Verification type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Verification verification = (Verification) o;
    return Objects.equals(this.applicationId, verification.applicationId) &&
        Objects.equals(this.attemptedHash, verification.attemptedHash) &&
        Objects.equals(this.auditLogEntryId, verification.auditLogEntryId) &&
        Objects.equals(this.created, verification.created) &&
        Objects.equals(this.failure, verification.failure) &&
        Objects.equals(this.id, verification.id) &&
        Objects.equals(this.type, verification.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationId, attemptedHash, auditLogEntryId, created, failure, id, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Verification {\n");
    
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    attemptedHash: ").append(toIndentedString(attemptedHash)).append("\n");
    sb.append("    auditLogEntryId: ").append(toIndentedString(auditLogEntryId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

