/*
 * LogSentinel RESTful API
 * Read more at http://localhost:8080/docs
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WhitelabelStyling
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-15T10:33:18.929+03:00")
public class WhitelabelStyling {
  @SerializedName("css")
  private String css = null;

  @SerializedName("domain")
  private String domain = null;

  @SerializedName("footer")
  private String footer = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("logo")
  private List<byte[]> logo = null;

  @SerializedName("title")
  private String title = null;

  public WhitelabelStyling css(String css) {
    this.css = css;
    return this;
  }

   /**
   * Get css
   * @return css
  **/
  @ApiModelProperty(value = "")
  public String getCss() {
    return css;
  }

  public void setCss(String css) {
    this.css = css;
  }

  public WhitelabelStyling domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain
  **/
  @ApiModelProperty(value = "")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public WhitelabelStyling footer(String footer) {
    this.footer = footer;
    return this;
  }

   /**
   * Get footer
   * @return footer
  **/
  @ApiModelProperty(value = "")
  public String getFooter() {
    return footer;
  }

  public void setFooter(String footer) {
    this.footer = footer;
  }

  public WhitelabelStyling key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public WhitelabelStyling logo(List<byte[]> logo) {
    this.logo = logo;
    return this;
  }

  public WhitelabelStyling addLogoItem(byte[] logoItem) {
    if (this.logo == null) {
      this.logo = new ArrayList<byte[]>();
    }
    this.logo.add(logoItem);
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  @ApiModelProperty(value = "")
  public List<byte[]> getLogo() {
    return logo;
  }

  public void setLogo(List<byte[]> logo) {
    this.logo = logo;
  }

  public WhitelabelStyling title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WhitelabelStyling whitelabelStyling = (WhitelabelStyling) o;
    return Objects.equals(this.css, whitelabelStyling.css) &&
        Objects.equals(this.domain, whitelabelStyling.domain) &&
        Objects.equals(this.footer, whitelabelStyling.footer) &&
        Objects.equals(this.key, whitelabelStyling.key) &&
        Objects.equals(this.logo, whitelabelStyling.logo) &&
        Objects.equals(this.title, whitelabelStyling.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(css, domain, footer, key, logo, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WhitelabelStyling {\n");
    
    sb.append("    css: ").append(toIndentedString(css)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    footer: ").append(toIndentedString(footer)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

